### ISSUE TITLE
Allow aliasing of plugin names

### ISSUE THREAD

**Issue by gtristan** [apache/buildstream#1556]
Currently the [plugin loading semantics](https://docs.buildstream.build/master/format_project.html#loading-plugins) allow for a lot of flexibility, but we have some minor limitations when it comes to loading plugins from multiple sources which might have namespace collisions.

In order to allow loading different plugins which have the same name, we should allow aliasing of plugin names.

A syntax to allow this might look like the following:

```yaml

# Normal plugin loading
plugins:
- origin: junction
  junction: plugin-junction.bst
  elements:
  - frobnicate
  - slurpshiggy
  - gizmoflooper

  # Load a second frobnicate element from another project,
  # locally we will address the element as "frobnicate2"
- origin: junction
  junction: another-plugin-junction.bst
  elements:
  - name: frobnicate
    alias: frobnicate2
```
