### ISSUE TITLE
BuildStream 1.6.3 compose build fails when integration command deletes directory

### ISSUE THREAD

**Issue by nanonyme** [apache/buildstream#1585]
While trying to integrate https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/7272 I got error like
I was given a completely unhelpful error message like
`1    [00:00:28] FAILURE snap-images/platform-snap-image.bst: Source file is missing: /var/home/nanonyme/.cache/buildstream/build/snap-images-platform-snap-image-_yoa1fqv/root/etc/fonts`
as a result.

**Comment by abderrahim** [comment]
I managed to find a small reproducer for this: take the following element

```
kind: manual

config:
  install-commands:
  - mkdir -p %{install-root}/etc/release
  - ln -s /etc/os-release %{install-root}/etc/release/

public:
  bst:
    integration-commands:
    - rm -r /etc
```
(and add as a dependency a minimal sysroot). A compose element that depends on this and requires split (to use the plugin terminology) will choke on this with a similar error.
```
FAILURE compose.bst: Source file is missing: /var/home/abderrahim/.cache/buildstream/build/compose-_fo9upgi/root/etc
```

The problem is that the `compute_manifest()` call [here](https://github.com/apache/buildstream/blob/bst-1/buildstream/plugins/elements/compose.py#L102) returns `.`, `etc` and `etc/release/os-release` (but no `etc/release`). After the integration command, it notices that `etc/release/os-release` has been removed, but not `/etc` (I guess it only checks files).

It seems the reason this is happening is because we have a symlink inside a directory, because it works fine if the symlink is directly in `/etc`.

This doesn't happen with bst master since 9f6a3332812f4caa036084f843cf95b9c6b9181f (part of [!1182](https://gitlab.com/BuildStream/buildstream/-/merge_requests/1182)) as it no longer tries to copy all files in the manifest but tries instead to check files with the manifest for copying.
