### ISSUE TITLE
ostree partially incompatible with new bst2 sandboxing

### ISSUE THREAD

**Issue by nanonyme** [apache/buildstream#1660]
Noticed by @abderrahim
I can reproduce this using the latest version of [!7038](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/7038) by running make run-ostree-vm. I get the following error:
```
error: Writing content object: Setting xattrs: fsetxattr(user.checksum.sha256): Operation not supported
Command 'ostree pull-local "/buildstream/freedesktop-sdk/vm/minimal-ostree/image.bst/source-repo" freedesktop
```

**Comment by gtristan** [comment]
Anything which you had permission to do when using bst 1, like setting `xattrs` (which will require root) should work equally with bst 2 *when executed in the same environment with the same privilidges*.

Maybe this usually works in CI under root user with bst1, but was tried as a regular user on a local workstation ?

Did this happen as a result of https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/abderrahim/bst2/elements/vm/minimal-ostree/image.bst#L35 ? or somewhere else ?

One thing I noticed is that this branch uses `ostree` from `bst-plugins-experimental` instead of from `buildstream-plugins`, which should be okay, but it also appears to use the `ostree_mirror` plugin, which simply does not exist anywhere:

```
  - origin: junction
    junction: plugins/bst-plugins-experimental.bst
    elements:
    - check_forbidden
    - collect_initial_scripts
    - collect_integration
    - collect_manifest
    - flatpak_image
    - flatpak_repo
    - makemaker
    - modulebuild
    - snap_image
    sources:
    - cpan
    - git_tag
    - git_module
    - ostree
    - ostree_mirror
    - patch_queue
    - pypi
    - zip
```
I checked the ref at `plugins/bst-plugins-experimental.bst` which appears to be at the tip of master, but there is no such plugin.

Given that this non-existent plugin is used by the very same element: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/abderrahim/bst2/elements/vm/minimal-ostree/image.bst#L102 it is hard to conceive of how the build got far enough to produce this error.

Can I get more information on how to reproduce this ?
