### ISSUE TITLE
Readonly filesytem /dev/tty

### ISSUE THREAD

**Issue by itsManjeet** [apache/buildstream#1779]
Hey, I am getting this error while building nvidia gpu drivers via buildstream==1.6.7
```
Creating directory /buildstream-install/nvidia
        Verifying archive integrity... OK
        Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 515.76./NVIDIA-Linux-x86_64-515.76.run: line 719: /dev/tty: Read-only file system
```

```yaml
kind: manual

sources:
- kind: remote
  url: http://uk.download.nvidia.com/XFree86/Linux-x86_64/515.76/NVIDIA-Linux-x86_64-515.76.run

  ref: c6a2a18ceb965f4980bce4e5cea36fd622cdc1a5f31a0eb1bbd359a9e9f6bf44
build-depends:
- freedesktop-sdk.bst:bootstrap-import.bst

config:
  install-commands:
  - |
    sh ./NVIDIA-*.run -x --target %{install-root}/nvidia
    sh ./NVIDIA-*.run --version-string > %{install-root}/nvidia/nvidiaver
    cd %{install-root}/nvidia && tar -xf nvidia-persistenced-init.tar.bz2

```

**freedesktop-sdk.bst** ref `freedesktop-sdk-22.08.2.1-0-gde68b5af1dc9ae9656b1b6647ba035d27743bd77`

## How to reproduce
- `bst build nvidia.bst`
